apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  selector:
    matchLabels:
      app: hotstar
  replicas: 3
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: manojkrishnappa/jiohotstar:20250406
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Adding health checks (customize the path and port as needed)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-service  # Updated name for clarity
spec:
  selector:
    app: hotstar
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer